version: "3.7"
services:
  db:
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_DATABASE: edgedb
      EDGEDB_SERVER_USER: edgedb
      EDGEDB_SERVER_PASSWORD: ${DB_SECRET}
      EDGEDB_SERVER_DATADIR: /var/lib/edgedb/data
      EDGEDB_SERVER_TLS_CERT_MODE: generate_self_signed
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
#      - "./credentials:/root/.config/edgedb/credentials"
      - "./data:/var/lib/edgedb/data"
    ports:
      - ${EDGEDB_DOCKER_PORT}:5656
  nextjs:
    env_file:
      - .env
    environment:
      EDGEDB_DSN: ${EDGEDB_DOCKER_DSN_OPTIONS}
      EDGEDB_CLIENT_TLS_SECURITY: ${EDGEDB_CLIENT_TLS_SECURITY}
    build:
      context: .
      args:
        EDGEDB_DSN: ${EDGEDB_DOCKER_DSN_OPTIONS}
        EDGEDB_CLIENT_TLS_SECURITY: ${EDGEDB_CLIENT_TLS_SECURITY}
    ports:
      - ${NEXTJS_DOCKER_PORT}:3000
#    command: "sh ./run.sh"
    depends_on:
      - db
